# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  example.com:
    site_hosts:
      - canonical: example.austin
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: dylancellison@gmail.com
    multisite:
      enabled: false
    ssl:
      enabled: false
    cache:
      enabled: false
